// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

package protobuf;

public interface IniciarOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serializacao.Iniciar)
    com.google.protobuf.MessageOrBuilder {
}
