// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

package protobuf;

/**
 * Protobuf type {@code serializacao.Mensagem}
 */
public  final class Mensagem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:serializacao.Mensagem)
    MensagemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Mensagem.newBuilder() to construct.
  private Mensagem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Mensagem() {
    nivel_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Mensagem();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Mensagem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            protobuf.PingMensagem.Builder subBuilder = null;
            if (ping_ != null) {
              subBuilder = ping_.toBuilder();
            }
            ping_ = input.readMessage(protobuf.PingMensagem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ping_);
              ping_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            protobuf.PongMensagem.Builder subBuilder = null;
            if (pong_ != null) {
              subBuilder = pong_.toBuilder();
            }
            pong_ = input.readMessage(protobuf.PongMensagem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pong_);
              pong_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            protobuf.Iniciar.Builder subBuilder = null;
            if (inicio_ != null) {
              subBuilder = inicio_.toBuilder();
            }
            inicio_ = input.readMessage(protobuf.Iniciar.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(inicio_);
              inicio_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            nivel_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.AkkaOuterClass.internal_static_serializacao_Mensagem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.AkkaOuterClass.internal_static_serializacao_Mensagem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.Mensagem.class, protobuf.Mensagem.Builder.class);
  }

  public static final int PING_FIELD_NUMBER = 1;
  private protobuf.PingMensagem ping_;
  /**
   * <code>.serializacao.PingMensagem ping = 1;</code>
   * @return Whether the ping field is set.
   */
  public boolean hasPing() {
    return ping_ != null;
  }
  /**
   * <code>.serializacao.PingMensagem ping = 1;</code>
   * @return The ping.
   */
  public protobuf.PingMensagem getPing() {
    return ping_ == null ? protobuf.PingMensagem.getDefaultInstance() : ping_;
  }
  /**
   * <code>.serializacao.PingMensagem ping = 1;</code>
   */
  public protobuf.PingMensagemOrBuilder getPingOrBuilder() {
    return getPing();
  }

  public static final int PONG_FIELD_NUMBER = 2;
  private protobuf.PongMensagem pong_;
  /**
   * <code>.serializacao.PongMensagem pong = 2;</code>
   * @return Whether the pong field is set.
   */
  public boolean hasPong() {
    return pong_ != null;
  }
  /**
   * <code>.serializacao.PongMensagem pong = 2;</code>
   * @return The pong.
   */
  public protobuf.PongMensagem getPong() {
    return pong_ == null ? protobuf.PongMensagem.getDefaultInstance() : pong_;
  }
  /**
   * <code>.serializacao.PongMensagem pong = 2;</code>
   */
  public protobuf.PongMensagemOrBuilder getPongOrBuilder() {
    return getPong();
  }

  public static final int INICIO_FIELD_NUMBER = 3;
  private protobuf.Iniciar inicio_;
  /**
   * <code>.serializacao.Iniciar inicio = 3;</code>
   * @return Whether the inicio field is set.
   */
  public boolean hasInicio() {
    return inicio_ != null;
  }
  /**
   * <code>.serializacao.Iniciar inicio = 3;</code>
   * @return The inicio.
   */
  public protobuf.Iniciar getInicio() {
    return inicio_ == null ? protobuf.Iniciar.getDefaultInstance() : inicio_;
  }
  /**
   * <code>.serializacao.Iniciar inicio = 3;</code>
   */
  public protobuf.IniciarOrBuilder getInicioOrBuilder() {
    return getInicio();
  }

  public static final int NIVEL_FIELD_NUMBER = 4;
  private int nivel_;
  /**
   * <code>.serializacao.Nivel nivel = 4;</code>
   * @return The enum numeric value on the wire for nivel.
   */
  public int getNivelValue() {
    return nivel_;
  }
  /**
   * <code>.serializacao.Nivel nivel = 4;</code>
   * @return The nivel.
   */
  public protobuf.Nivel getNivel() {
    @SuppressWarnings("deprecation")
    protobuf.Nivel result = protobuf.Nivel.valueOf(nivel_);
    return result == null ? protobuf.Nivel.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ping_ != null) {
      output.writeMessage(1, getPing());
    }
    if (pong_ != null) {
      output.writeMessage(2, getPong());
    }
    if (inicio_ != null) {
      output.writeMessage(3, getInicio());
    }
    if (nivel_ != protobuf.Nivel.BAIXO.getNumber()) {
      output.writeEnum(4, nivel_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ping_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPing());
    }
    if (pong_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPong());
    }
    if (inicio_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getInicio());
    }
    if (nivel_ != protobuf.Nivel.BAIXO.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, nivel_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.Mensagem)) {
      return super.equals(obj);
    }
    protobuf.Mensagem other = (protobuf.Mensagem) obj;

    if (hasPing() != other.hasPing()) return false;
    if (hasPing()) {
      if (!getPing()
          .equals(other.getPing())) return false;
    }
    if (hasPong() != other.hasPong()) return false;
    if (hasPong()) {
      if (!getPong()
          .equals(other.getPong())) return false;
    }
    if (hasInicio() != other.hasInicio()) return false;
    if (hasInicio()) {
      if (!getInicio()
          .equals(other.getInicio())) return false;
    }
    if (nivel_ != other.nivel_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPing()) {
      hash = (37 * hash) + PING_FIELD_NUMBER;
      hash = (53 * hash) + getPing().hashCode();
    }
    if (hasPong()) {
      hash = (37 * hash) + PONG_FIELD_NUMBER;
      hash = (53 * hash) + getPong().hashCode();
    }
    if (hasInicio()) {
      hash = (37 * hash) + INICIO_FIELD_NUMBER;
      hash = (53 * hash) + getInicio().hashCode();
    }
    hash = (37 * hash) + NIVEL_FIELD_NUMBER;
    hash = (53 * hash) + nivel_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.Mensagem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.Mensagem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.Mensagem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.Mensagem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.Mensagem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.Mensagem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.Mensagem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.Mensagem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.Mensagem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.Mensagem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.Mensagem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.Mensagem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.Mensagem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code serializacao.Mensagem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:serializacao.Mensagem)
      protobuf.MensagemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.AkkaOuterClass.internal_static_serializacao_Mensagem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.AkkaOuterClass.internal_static_serializacao_Mensagem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.Mensagem.class, protobuf.Mensagem.Builder.class);
    }

    // Construct using protobuf.Mensagem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (pingBuilder_ == null) {
        ping_ = null;
      } else {
        ping_ = null;
        pingBuilder_ = null;
      }
      if (pongBuilder_ == null) {
        pong_ = null;
      } else {
        pong_ = null;
        pongBuilder_ = null;
      }
      if (inicioBuilder_ == null) {
        inicio_ = null;
      } else {
        inicio_ = null;
        inicioBuilder_ = null;
      }
      nivel_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.AkkaOuterClass.internal_static_serializacao_Mensagem_descriptor;
    }

    @java.lang.Override
    public protobuf.Mensagem getDefaultInstanceForType() {
      return protobuf.Mensagem.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.Mensagem build() {
      protobuf.Mensagem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.Mensagem buildPartial() {
      protobuf.Mensagem result = new protobuf.Mensagem(this);
      if (pingBuilder_ == null) {
        result.ping_ = ping_;
      } else {
        result.ping_ = pingBuilder_.build();
      }
      if (pongBuilder_ == null) {
        result.pong_ = pong_;
      } else {
        result.pong_ = pongBuilder_.build();
      }
      if (inicioBuilder_ == null) {
        result.inicio_ = inicio_;
      } else {
        result.inicio_ = inicioBuilder_.build();
      }
      result.nivel_ = nivel_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.Mensagem) {
        return mergeFrom((protobuf.Mensagem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.Mensagem other) {
      if (other == protobuf.Mensagem.getDefaultInstance()) return this;
      if (other.hasPing()) {
        mergePing(other.getPing());
      }
      if (other.hasPong()) {
        mergePong(other.getPong());
      }
      if (other.hasInicio()) {
        mergeInicio(other.getInicio());
      }
      if (other.nivel_ != 0) {
        setNivelValue(other.getNivelValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.Mensagem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.Mensagem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private protobuf.PingMensagem ping_;
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.PingMensagem, protobuf.PingMensagem.Builder, protobuf.PingMensagemOrBuilder> pingBuilder_;
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     * @return Whether the ping field is set.
     */
    public boolean hasPing() {
      return pingBuilder_ != null || ping_ != null;
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     * @return The ping.
     */
    public protobuf.PingMensagem getPing() {
      if (pingBuilder_ == null) {
        return ping_ == null ? protobuf.PingMensagem.getDefaultInstance() : ping_;
      } else {
        return pingBuilder_.getMessage();
      }
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    public Builder setPing(protobuf.PingMensagem value) {
      if (pingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ping_ = value;
        onChanged();
      } else {
        pingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    public Builder setPing(
        protobuf.PingMensagem.Builder builderForValue) {
      if (pingBuilder_ == null) {
        ping_ = builderForValue.build();
        onChanged();
      } else {
        pingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    public Builder mergePing(protobuf.PingMensagem value) {
      if (pingBuilder_ == null) {
        if (ping_ != null) {
          ping_ =
            protobuf.PingMensagem.newBuilder(ping_).mergeFrom(value).buildPartial();
        } else {
          ping_ = value;
        }
        onChanged();
      } else {
        pingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    public Builder clearPing() {
      if (pingBuilder_ == null) {
        ping_ = null;
        onChanged();
      } else {
        ping_ = null;
        pingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    public protobuf.PingMensagem.Builder getPingBuilder() {
      
      onChanged();
      return getPingFieldBuilder().getBuilder();
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    public protobuf.PingMensagemOrBuilder getPingOrBuilder() {
      if (pingBuilder_ != null) {
        return pingBuilder_.getMessageOrBuilder();
      } else {
        return ping_ == null ?
            protobuf.PingMensagem.getDefaultInstance() : ping_;
      }
    }
    /**
     * <code>.serializacao.PingMensagem ping = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.PingMensagem, protobuf.PingMensagem.Builder, protobuf.PingMensagemOrBuilder> 
        getPingFieldBuilder() {
      if (pingBuilder_ == null) {
        pingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protobuf.PingMensagem, protobuf.PingMensagem.Builder, protobuf.PingMensagemOrBuilder>(
                getPing(),
                getParentForChildren(),
                isClean());
        ping_ = null;
      }
      return pingBuilder_;
    }

    private protobuf.PongMensagem pong_;
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.PongMensagem, protobuf.PongMensagem.Builder, protobuf.PongMensagemOrBuilder> pongBuilder_;
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     * @return Whether the pong field is set.
     */
    public boolean hasPong() {
      return pongBuilder_ != null || pong_ != null;
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     * @return The pong.
     */
    public protobuf.PongMensagem getPong() {
      if (pongBuilder_ == null) {
        return pong_ == null ? protobuf.PongMensagem.getDefaultInstance() : pong_;
      } else {
        return pongBuilder_.getMessage();
      }
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    public Builder setPong(protobuf.PongMensagem value) {
      if (pongBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pong_ = value;
        onChanged();
      } else {
        pongBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    public Builder setPong(
        protobuf.PongMensagem.Builder builderForValue) {
      if (pongBuilder_ == null) {
        pong_ = builderForValue.build();
        onChanged();
      } else {
        pongBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    public Builder mergePong(protobuf.PongMensagem value) {
      if (pongBuilder_ == null) {
        if (pong_ != null) {
          pong_ =
            protobuf.PongMensagem.newBuilder(pong_).mergeFrom(value).buildPartial();
        } else {
          pong_ = value;
        }
        onChanged();
      } else {
        pongBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    public Builder clearPong() {
      if (pongBuilder_ == null) {
        pong_ = null;
        onChanged();
      } else {
        pong_ = null;
        pongBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    public protobuf.PongMensagem.Builder getPongBuilder() {
      
      onChanged();
      return getPongFieldBuilder().getBuilder();
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    public protobuf.PongMensagemOrBuilder getPongOrBuilder() {
      if (pongBuilder_ != null) {
        return pongBuilder_.getMessageOrBuilder();
      } else {
        return pong_ == null ?
            protobuf.PongMensagem.getDefaultInstance() : pong_;
      }
    }
    /**
     * <code>.serializacao.PongMensagem pong = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.PongMensagem, protobuf.PongMensagem.Builder, protobuf.PongMensagemOrBuilder> 
        getPongFieldBuilder() {
      if (pongBuilder_ == null) {
        pongBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protobuf.PongMensagem, protobuf.PongMensagem.Builder, protobuf.PongMensagemOrBuilder>(
                getPong(),
                getParentForChildren(),
                isClean());
        pong_ = null;
      }
      return pongBuilder_;
    }

    private protobuf.Iniciar inicio_;
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.Iniciar, protobuf.Iniciar.Builder, protobuf.IniciarOrBuilder> inicioBuilder_;
    /**
     * <code>.serializacao.Iniciar inicio = 3;</code>
     * @return Whether the inicio field is set.
     */
    public boolean hasInicio() {
      return inicioBuilder_ != null || inicio_ != null;
    }
    /**
     * <code>.serializacao.Iniciar inicio = 3;</code>
     * @return The inicio.
     */
    public protobuf.Iniciar getInicio() {
      if (inicioBuilder_ == null) {
        return inicio_ == null ? protobuf.Iniciar.getDefaultInstance() : inicio_;
      } else {
        return inicioBuilder_.getMessage();
      }
    }
    /**
     * <code>.serializacao.Iniciar inicio = 3;</code>
     */
    public Builder setInicio(protobuf.Iniciar value) {
      if (inicioBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inicio_ = value;
        onChanged();
      } else {
        inicioBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.Iniciar inicio = 3;</code>
     */
    public Builder setInicio(
        protobuf.Iniciar.Builder builderForValue) {
      if (inicioBuilder_ == null) {
        inicio_ = builderForValue.build();
        onChanged();
      } else {
        inicioBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serializacao.Iniciar inicio = 3;</code>
     */
    public Builder mergeInicio(protobuf.Iniciar value) {
      if (inicioBuilder_ == null) {
        if (inicio_ != null) {
          inicio_ =
            protobuf.Iniciar.newBuilder(inicio_).mergeFrom(value).buildPartial();
        } else {
          inicio_ = value;
        }
        onChanged();
      } else {
        inicioBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.Iniciar inicio = 3;</code>
     */
    public Builder clearInicio() {
      if (inicioBuilder_ == null) {
        inicio_ = null;
        onChanged();
      } else {
        inicio_ = null;
        inicioBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serializacao.Iniciar inicio = 3;</code>
     */
    public protobuf.Iniciar.Builder getInicioBuilder() {
      
      onChanged();
      return getInicioFieldBuilder().getBuilder();
    }
    /**
     * <code>.serializacao.Iniciar inicio = 3;</code>
     */
    public protobuf.IniciarOrBuilder getInicioOrBuilder() {
      if (inicioBuilder_ != null) {
        return inicioBuilder_.getMessageOrBuilder();
      } else {
        return inicio_ == null ?
            protobuf.Iniciar.getDefaultInstance() : inicio_;
      }
    }
    /**
     * <code>.serializacao.Iniciar inicio = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.Iniciar, protobuf.Iniciar.Builder, protobuf.IniciarOrBuilder> 
        getInicioFieldBuilder() {
      if (inicioBuilder_ == null) {
        inicioBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protobuf.Iniciar, protobuf.Iniciar.Builder, protobuf.IniciarOrBuilder>(
                getInicio(),
                getParentForChildren(),
                isClean());
        inicio_ = null;
      }
      return inicioBuilder_;
    }

    private int nivel_ = 0;
    /**
     * <code>.serializacao.Nivel nivel = 4;</code>
     * @return The enum numeric value on the wire for nivel.
     */
    public int getNivelValue() {
      return nivel_;
    }
    /**
     * <code>.serializacao.Nivel nivel = 4;</code>
     * @param value The enum numeric value on the wire for nivel to set.
     * @return This builder for chaining.
     */
    public Builder setNivelValue(int value) {
      nivel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.serializacao.Nivel nivel = 4;</code>
     * @return The nivel.
     */
    public protobuf.Nivel getNivel() {
      @SuppressWarnings("deprecation")
      protobuf.Nivel result = protobuf.Nivel.valueOf(nivel_);
      return result == null ? protobuf.Nivel.UNRECOGNIZED : result;
    }
    /**
     * <code>.serializacao.Nivel nivel = 4;</code>
     * @param value The nivel to set.
     * @return This builder for chaining.
     */
    public Builder setNivel(protobuf.Nivel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      nivel_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.serializacao.Nivel nivel = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNivel() {
      
      nivel_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:serializacao.Mensagem)
  }

  // @@protoc_insertion_point(class_scope:serializacao.Mensagem)
  private static final protobuf.Mensagem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.Mensagem();
  }

  public static protobuf.Mensagem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Mensagem>
      PARSER = new com.google.protobuf.AbstractParser<Mensagem>() {
    @java.lang.Override
    public Mensagem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Mensagem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Mensagem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Mensagem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.Mensagem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

